# Generated by Django 6.1.1 on 2026-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_categoria_alter_produto_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('perifericos', 'Periféricos'), ('hardware', 'Hardware'), ('monitores', 'Monitores'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], default='outros', max_length=100),
        ),
    ]
